### ISSUE TITLE
Problems with subcommand args

### ISSUE THREAD

**Issue by zeroXten** [pki-io/admin#1]
I added the following line to the usage under "Examples":

    pki.io init --org=<org> --admin=<admin>

Then, when running I just got the generic usage:

    $ go run *.go init --org hello --admin fscott
    Usage:
        pki.io [--version] <command> [<args>...]
    exit status 1

Running this worked:

    $ go run *.go init 
    map[<command>:init <args>:[] --version:false]
    command arguments:
    []
    init
    Hi
    Not Implemented ...yet
    exit status 1

In order to get this working I had to reformat the usage a bit:

    usage := `pki.io
    Usage:
      pki.io init --org=<org> --admin=<admin>
      pki.io --version
 
    Options:
      -h --help   Show this screen
      --version   Show version
      --org=<name> Organisation name
      --admin=<name> Administrator name
    `

But that meant not using a subcommand function:

        arguments, _ := docopt.Parse(usage, nil, true, "pki.io", false)
        fmt.Println(arguments)

        if arguments["init"].(bool) {
            runInit(arguments)
        }

Here is the output...

    $ go run *.go init --org test --admin babc
    map[init:true --org:test --admin:babc --version:false]
    &{.}
    Creating Org entity
    Creating Admin entity
    Generating Org keys

**Comment by zeroXten** [comment]
Implementation should be modelled on this https://github.com/docopt/docopt.go/blob/master/examples/git/git.go

So, top level usage and parsing, and per-command usage and parsing.

**Comment by zeroXten** [comment]
Stealing this as I'm trying to work out the CLI UX anyway.

**Comment by jonbonazza** [comment]
Havent looked at the existing code,  but the flags package might be useful
here.

**Comment by thanasisk** [comment]
Hi Jon,
early in the project we decided to use a 3rd party library for command line parsing

**Comment by jonbonazza** [comment]
Ah okay, that makes sense. I actually haven't looked at clarg parsing libs
yet for golang. I'll have to check them out.

**Comment by zeroXten** [comment]
I think this is done now. Multi level docopt seems to work nicely.
