### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by zeroXten** [pki-io/admin#3]
Need to look at nice logging packages (or built in?) and choose one for CLI. Presume packages will continue to just return an error with fmt.Errorf() but at the moment we've just been doing panic() in the CLI.

**Comment by zeroXten** [comment]
This has been started now, using seelog. Need to choose some sort of default logger.

**Comment by jonbonazza** [comment]
Yea, for the default logger, I don't think there is a way to initialize a logging interface directly, but we can do it from string, so we could embed some default config in a constant and then in the init() function (where I am setting the logger to seelog.Disabled right now), we can initialize the logger global variable from the string.

**Comment by zeroXten** [comment]
Makes sense. It should probably log to STDERR, up to and including INFO by default using a fairly clean format. Perhaps no timestamp.

**Comment by jonbonazza** [comment]
Okay. That's simple enough. No debug logging by default then?

**Comment by jonbonazza** [comment]
Also,  do we want anything fancy for defaults,  such as rolling file? File
archiving? For that matter do we want to enable files by default at all or
just console output?

**Comment by thanasisk** [comment]
I would vote for a timestamp

**Comment by zeroXten** [comment]
Fair enough, keep it in. This is just for default, running a command output. Like running apt, vagrant, openssl etc.

**Comment by jonbonazza** [comment]
I think for default we should treat it like a command output like Fraser
mentioned. So no timestamp or log level display. It would be the same as if
we were just doing fmt.Println().

Then they can override with their own formats and rolling files and
archiving, etc..

**Comment by thanasisk** [comment]
Ok, no timestamp then, given eventually it will be an API client.

**Comment by zeroXten** [comment]
This is in place now with nice default logging.
