### ISSUE TITLE
The Makefile should be the single user interface for all build tasks

### ISSUE THREAD

**Issue by zeroXten** [pki-io/admin#32]
Do everything gom related via the make file. That way, if we replaced gom with something else, then interface would stay the same. ie it would still be "make get-deps && make build && make test && make install" regardless of what we use under the hood.

**Comment by zeroXten** [comment]
Just pushed a fix for the travis file to my registration-flow branch, so that will be included in the PR.

**Comment by thanasisk** [comment]
Yep, saw it. +1 for this change.
