### ISSUE TITLE
make command should run tests

### ISSUE THREAD

**Issue by zeroXten** [pki-io/admin#33]
Standard Makefile usage for working with source generally looks like

    $ make && make install

Therefore we need to ensure that the make command (no arguments) does:

* Get any dependencies
* Runs any tests
* Builds binaries

This also works nicely with TravisCI.

**Comment by thanasisk** [comment]
is this not taken care of in current version?

**Comment by zeroXten** [comment]
Yeah, I'll close this one. Although I won't close https://github.com/pki-io/admin/issues/32 yet as the master Makefile doesn't install dependencies at the moment and the travis.yml file needs to update to use make more.
