### ISSUE TITLE
Export certificates

### ISSUE THREAD

**Issue by zeroXten** [pki-io/admin#44]
Write tar.gz of selected data to default file, provided file or standard out.

**Comment by zeroXten** [comment]
Plan is to export to a default tar.gz file with the option to override the file using a switch (e.g. --file). If the switch value is - then the tar.gz is written to STDOTU so that it can be piped to openssl, GPG, keybase etc.

**Comment by jonbonazza** [comment]
Sounds good.

**Comment by zeroXten** [comment]
I've created a little test script here: https://gist.github.com/zeroXten/c051facd275971194303

Example use here: https://gist.github.com/zeroXten/88267e7a935c545f7701

Just need to find a nice way of making it usable. I guess a function that takes an array of ExportFile structs as input.

**Comment by zeroXten** [comment]
Well, its in there now and used by "node show". Closing this ticket as we can raise individual issues as required.
